### ISSUE TITLE
Use Qt6

### ISSUE THREAD

**Issue by evanmohr** [ashuntu/prismlauncher-snap#4]
[Prism Launcher is moving away from Qt5](https://github.com/PrismLauncher/PrismLauncher/issues/2324) and the [flatpak version is already using Qt6](https://github.com/flathub/org.prismlauncher.PrismLauncher/commit/d0e468b687c641786a0e4458bcc851b487006f91).

**Comment by ashuntu** [comment]
Initial build for QT 6 should be on the edge channel soon.

https://github.com/ashuntu/prismlauncher-snap/commit/b9318db9d8c29d107a156f77de8e1a3692a7922b
